### ISSUE TITLE
Fix typo in memory cache logic

### ISSUE THREAD

**Issue by pkan** [AvisoNovate/twixt#26]
In the condition `(< (+ cached-at check-interval-ms) now)` on line 99 of `io.aviso.twixt.memory-cache`, the less-than should be changed to greater-than.

The intent behind the logic is clearly documented, and isn't in doubt: within a certain time interval, the memory cache should return its `cached-asset`, and after the end of that interval, 
>  the delegate asset handler is used to see if the asset has changed, replacing it in the cache.

That is done in the call to `update-cache` below.  The purpose of the interval seems to be to avoid the possibility of making many costly filesystem calls, at the expense of slightly delaying the refreshing of externally-modified assets.  It is a very reasonable thing to do.

The less-than sign is clearly a typo.  You can see this by evaluating the above condition for very large value of `now`; the result will be `true`.  This means that no matter how long you wait, the memory cache wrapper will continue to return its cached asset (if it has one), even if that asset has been changed on the filesystem.  This is obviously not intended, and can be a big problem in some usage scenarios.

P.S. apologies for the delay in getting back to you about this

**Comment by tcoakley1** [comment]
Thanks @pkan 

This is now fixed -https://github.com/AvisoNovate/twixt/commit/383ef7b2d619ead7733a3095a14e110a45c4a082

and release 0.1.23 will be available shortly!

**Comment by pkan** [comment]
Thank you, @tcoakley1.

**Comment by clyfe** [comment]
Go with 0.1.24
